# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259d864b91a5abc1519c4eba24807d04816f28e382ed4a7977c6b92bae315a9a6ab6aa86ef80838ed05dbf0e05bd358bb58930dd22edcdd66139e2aa36e08d40

test:
  secret_key_base: d9dee1a5815a26ff0348fde6be444bd1c96ff2194a9b5a1cffca2365f97a827d1cd8ca6d656f4d62a2aaf5aa593b002757cb805dc3f50e7a3304f9bb2f86bacb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
